SRGSSR/pillarbox-web-suite

- package-lock.json
- packages/pillarbox-playlist/.babelrc
- packages/pillarbox-playlist/README.md
- packages/pillarbox-playlist/index.html
- packages/pillarbox-playlist/package.json
- packages/pillarbox-playlist/src/pillarbox-playlist.js
- packages/pillarbox-playlist/test/pillarbox-playlist.spec.js
- packages/pillarbox-playlist/vite.config.js
- packages/pillarbox-playlist/vite.config.lib.js
- packages/skip-button/index.html
- scripts/template/README.md.hbs
Introduces a pillarbox playlist plugin. This plugin supports playlist loading, dynamic modifications, auto-advancement, and repeat functionalities. 
- **Initialization Options**: Configurable through an options object that can include an initial playlist, and settings for repeat and auto-advance behaviors.
- **Dynamic Playlist Management**: Methods to load, push, splice, and shuffle playlist items dynamically.
- **Playback Control**: Functions to navigate through the playlist such as next, previous, and select specific items.
- **State Properties**: Properties like `repeat` and `autoadvance` which can be toggled post-initialization to alter playback behavior.
```javascript
import Pillarbox from '@srgssr/pillarbox-web';
import '@srgssr/pillarbox-playlist';
const player = new …
```
> feat: add playlist management plugin to pillarbox player

- package-lock.json
- package.json
- packages/pillarbox-playlist/src/lang/index.js
- packages/pillarbox-playlist/test/language.spec.js
- packages/pillarbox-playlist/vite.config.ui.js
- packages/skip-button/src/lang/index.js
- packages/skip-button/test/language.spec.js
- packages/skip-button/vite.config.lib.js
- scripts/create.js
- scripts/template/src/lang/index.js.hbs
- scripts/template/test/language.spec.js.hbs
- scripts/template/vite.config.lib.js.hbs
Refactored language modules to merge with existing default translations in `videojs.options.language`. This prevents overriding default configurations when calling `videojs.addLanguage`. Changes have been applied across all packages in the monorepo and the templates for the generation of new packages.
- Preserve existing translations when adding package specific keys.
- Expose language files as assets into the final build.
> fix: preserve default options when adding new translations

- packages/pillarbox-playlist/README.md
- packages/pillarbox-playlist/src/pillarbox-playlist.js
- packages/pillarbox-playlist/test/pillarbox-playlist.spec.js
Resolves #17 by implementing smart navigation to the previous item in the playlist based on the current playback position:
- If playback is beyond the threshold, the current media is restarted.
- If playback is within the threshold, the previous item is navigated to.
- For live media, the previous items is always played regardless of the current playback position.
- The threshold functionality can be disabled by setting the value to undefined.
Example usage:
```javascript
import pillarbox from '@srgssr/pillarbox-web';
import './src/pillarbox-playlist-ui.js';
window.player = pillarbox('player', {
plugins: {
pillarboxPlaylist: {
// The threshold in seconds
previousNavigationThreshold: 10
}
}
});
```
- Adapted the previous function to observe the threshold value.
- Added the possibility to …
> feat(playlist-plugin): implement smart navigation based on playback position

- .github/workflows/github-page.yml
- .github/workflows/preview.yml
- .github/workflows/quality.yml
- .github/workflows/release.yml
- docs/README.md
- package-lock.json
- package.json
- packages/pillarbox-playlist/LICENSE
- packages/pillarbox-playlist/README.md
- packages/pillarbox-playlist/package.json
- packages/skip-button/LICENSE
- packages/skip-button/README.md
- packages/skip-button/package.json
- scripts/create.js
- scripts/template/LICENSE
- scripts/template/README.md.hbs
- scripts/template/package.json.hbs
Automated the process of publishing pillarbox-suite packages to npm by updating necessary configurations and workflows.
- Updated GitHub Actions workflows to automate the publishing process to npm.
- Modified package.json files to ensure correct npm configuration.
- Added a LICENSE file to each package and updated the `create` script to automatically include one.
> fix: publish pillarbox-suite to npm

- packages/pillarbox-playlist/README.md
- packages/pillarbox-playlist/package.json
- packages/skip-button/README.md
- packages/skip-button/package.json
- scripts/template/README.md.hbs
- scripts/template/package.json.hbs
- Fixes all the links to the quick start guide of pillarbox-web.
- Makes the homepage point to the readme file in github for each individual package instead of the demo page for better discoverability.
- Fixes links to contributing guidelines.
> docs: fix quick start link

- docs/README.md
- index.html
- package.json
- scripts/prepare-deployment.js
Resolves #15 by making it easier to develop and deploy the project with a single command from the root directory.
- Simplify the prepare script to copy necessary files.
- Add a root-level index.html to ensure Vite serves the correct page when running `npm run start`.
- Enhance the `github:page` script to build with vite before preparing the deployment.
> chore: streamline project startup and deployment process

- packages/pillarbox-playlist/README.md
- packages/pillarbox-playlist/index.html
- packages/pillarbox-playlist/scss/pillarbox-playlist.scss
- packages/pillarbox-playlist/src/components/modal/pillarbox-playlist-menu-item.js
- packages/pillarbox-playlist/src/components/modal/pillarbox-playlist-next-item-button.js
- packages/pillarbox-playlist/src/components/modal/pillarbox-playlist-repeat-button.js
- packages/pillarbox-playlist/src/components/modal/pillarbox-playlist-shuffle-button.js
- packages/pillarbox-playlist/src/components/modal/pillarbox-previous-item-button.js
- packages/pillarbox-playlist/src/components/pillarbox-playlist-button.js
- packages/pillarbox-playlist/src/lang/de.json
- packages/pillarbox-playlist/src/lang/en.json
- packages/pillarbox-playlist/src/lang/fr.json
- packages/pillarbox-playlist/src/lang/it.json
- packages/pillarbox-playlist/src/lang/rm.json
- packages/pillarbox-playlist/src/pillarbox-playlist-ui.js
- packages/pillarbox-playlist/src/pillarbox-playlist.js
- packages/pillarbox-playlist/test/pillarbox-playlist-ui.spec.js
- packages/pillarbox-playlist/test/pillarbox-playlist.spec.js
Resolves #19 by introducing a new "repeat one" mode to the playlist plugin.
The UI has been modified to include a toggle button that cycles through three modes: no repeat, repeat all, and repeat one. See the following example:
https://github.com/user-attachments/assets/843f23c1-2229-4cff-97cd-23e75b3df3bd
**BREAKING CHANGE**:
- Changed the API to toggle the repeat mode and the initialisation options.
- The repeat mode is no longer a boolean. It is now a number representing each mode (0: no repeat, 1: repeat all, 2: repeat one).
> feat(playlist-plugin): introduce repeat one mode

- packages/pillarbox-playlist/src/pillarbox-playlist.js
- packages/skip-button/src/skip-button.js
- scripts/template/src/{{kebabCase name}}.js.hbs
Exposes the version in the package.json of each existing plugin and component. Modified the create script template so that the `VERSION` is automatically added on every new package.
- **Retrieve the version of a component:**
```javascript
player.SkipButton.constructor.VERSION
```
- **Retrieve the version of a plugin:**
```javascript
player.pillarboxPlaylist().version()
```
- Updates create script template to include the version of the generated component or plugin.
- Expose the skip-button component version by adding a `VERSION` property to the constructor.
- Expose the playlist-plugin version by adding a `VERSION` property to the constructor.
> fix: expose version on existing plugins and components

- .husky/commit-msg
- .husky/pre-commit
- .husky/pre-push
- docs/README.md
- packages/pillarbox-playlist/src/pillarbox-playlist.js
- packages/pillarbox-playlist/test/pillarbox-playlist.spec.js
Resolves #32 by adding logic to loop to the last element when navigating backwards from the first item in the playlist while Repeat All is enabled.
-  Remove deprecated lines in husky hooks, See ["How to Migrate"](https://github.com/typicode/husky/releases/tag/v9.0.1).
- Added tests for both `next` and `previous` functions when Repeat All mode is enabled.
> feat: bidirectional looping when repeat all is enabled

- packages/pillarbox-playlist/src/pillarbox-playlist.js
- packages/pillarbox-playlist/test/pillarbox-playlist.spec.js
Replaced hardcoded value `3` to improve maintainability and adapt to changes in RepeatMode. See https://github.com/SRGSSR/pillarbox-web-suite/pull/33#pullrequestreview-2381337306
- Added a test to ensure the change works as expected.
> chore(playlist-plugin): use dynamic repeat mode length in toggle calculation

- packages/user-preferences/scss/user-preferences.scss
The package build does not work if the scss folder and the associated style file are not present.
- create scss folder
- create scss file and add a comment to satisfy the linter
> fix(user-preferences): failed build step when the SCSS folder and file are missing

- package-lock.json
- scripts/create.js
- scripts/template/README.md.hbs
- scripts/template/index.html.hbs
- scripts/template/package.json.hbs
- scripts/test/create.spec.js
Add a new prompt in the component generator to allow opting out of SCSS when creating a new element.
When SCSS is disabled, the generated component will skip the SCSS-to-CSS compilation step, adjust the package configuration to avoid exporting any CSS file, and no SCSS file will be created by default.
- Added a prompt to opt-out of the SCSS generation.
> chore(create): allow opt-out of scss on new component

- packages/pillarbox-debug-panel/package.json
- packages/pillarbox-debug-panel/vite.config.umd.js
- packages/pillarbox-playlist/package.json
- packages/pillarbox-playlist/vite.config.ui.js
- packages/pillarbox-playlist/vite.config.umd.js
- packages/pillarbox-playlist/vite.config.umd.ui.js
- packages/skip-button/package.json
- packages/skip-button/vite.config.umd.js
- packages/user-preferences/vite.config.umd.js
- scripts/template/package.json.hbs
- scripts/template/vite.config.umd.js.hbs
New and old components can now be loaded via a CDN (e.g., jsDelivr) using a simple <script> tag, enabling easier integration in external projects.
This PR makes sure that all new an existing UMD builds use the common babel configuration to align the compatibility requirements to those of the pillarbox-web player.
- Added UMD build generation for new components.
- `pillarbox-debug-panel`: add specific browser export property to the package.json.
- `user-preferences`: align browser compatibility with Bable for the UMD build.
- Add a UMD build for both the `pillarbox-playlist` plugin and the `skip-button` component. An additional `ui` specific 
build has been added to the pillarox-playlist plugin since this plugin allows to integration without the visual component.
> chore(create): generate umd build

- index.html
- package-lock.json
- packages/big-replay-button/.babelrc
- packages/big-replay-button/.releaserc
- packages/big-replay-button/LICENSE
- packages/big-replay-button/README.md
- packages/big-replay-button/index.html
- packages/big-replay-button/package.json
- packages/big-replay-button/scss/big-replay-button.scss
- packages/big-replay-button/src/big-replay-button.js
- packages/big-replay-button/test/big-replay-button.spec.js
- packages/big-replay-button/vite.config.js
- packages/big-replay-button/vite.config.lib.js
- packages/big-replay-button/vite.config.umd.js
Resolves #38 by introducing a `BigReplayButton` component for the video.js player.
This component extends the existing BigPlayButton and is displayed only when the video has ended. With this approach we maintain accessibility standards and minimize the need for additional styling from integrators.
Key features:
- Displays a replay button when the video ends.
- Hides the button during playback or pause states.
- Allows styling reuse for projects already using the BigPlayButton.
- Sets the control text to "Replay" and the icon to a replay symbol.
> feat(big-replay-button): publish replay button

- packages/big-replay-button/README.md
- packages/big-replay-button/test/big-replay-button.spec.js
- packages/pillarbox-debug-panel/README.md
- packages/pillarbox-debug-panel/test/pillarbox-debug-panel.spec.js
- packages/pillarbox-playlist/src/pillarbox-playlist-ui.js
- packages/pillarbox-playlist/test/pillarbox-playlist-ui.spec.js
- packages/pillarbox-playlist/test/pillarbox-playlist.spec.js
- packages/skip-button/README.md
- packages/skip-button/index.html
- packages/skip-button/test/skip-button.spec.js
- packages/user-preferences/README.md
- packages/user-preferences/test/user-preferences.spec.js
- scripts/template/README.md.hbs
- scripts/template/index.html.hbs
- scripts/template/test/{{kebabCase name}}.spec.js.hbs
Use preferred camel case in examples, tests and documentation.
Changed every component's initialization in examples and documentation from proper case to the preferred camel case. This change also applies to the templates of the `create` cli.
> chore: use camel case for examples and documentation

- packages/thumbnail-preview/src/components/thumbnail-preview-overlay.js
Remove braces from pointer event listeners, only one event is listened to.
> fix(thumbnail-preview): remove braces from listeners

- scripts/template/src/{{kebabCase name}}.js.hbs
Resolves #82 by removing the options parameter on generated Plugins constructor.
> chore(create): remove options from plugin generation

- packages/google-cast-sender/index.html
This PR allows us to pass a receiver application ID as a parameter, enabling us to test receivers other than the production one.
- A `receiverId` parameter has been added.
> chore(cast): allow passing a receiver application ID as a parameter

- packages/google-cast-sender/src/google-cast-tech.js
- packages/google-cast-sender/test/google-cast-tech.spec.js
Change the player's local state when a `PAUSED` event is emitted by the receiver.
- add a `handlePause` function
- add a test case
> feat(google-cast-sender): handle receiver paused event

- packages/google-cast-sender/src/google-cast-tech.js
- packages/google-cast-sender/test/google-cast-tech.spec.js
Resolves #94 by adding the ability to replay the media when it reaches the end. This feature relies on the media that was previously loaded locally. The reason is that when the receiver reaches the end of playback, the media session is removed.
- update the `play` function to allow reloading the media when it reaches the end of playback and the `replay` button is shown
- update the `ended` function to return `undefined` if no source is loaded
- update unit tests
> feat(google-cast-sender): add the ability to replay media

- packages/pillarbox-playlist/README.md
Resolves #77 by expanding the API documentation to include a dedicated PlaylistItem section, and improved the User Interface plugin docs by documenting recognized `data` fields, and providing an example of how to build a playlist with titles and durations that display in the UI.
> docs: add playlist item api documentation

- packages/svg-button/src/svg-icon-loader.js
- packages/svg-button/test/svg-button.spec.js
- packages/svg-button/test/svg-component.spec.js
Makes sure that the icon property takes precedence over the iconName for the `SvgButton` and `SvgComponent` components.
> fix(svg-button): icon property should take precedence over icon name

- packages/pillarbox-playlist/README.md
- packages/pillarbox-playlist/package.json
- packages/pillarbox-playlist/scss/pillarbox-playlist.scss
- packages/pillarbox-playlist/src/components/modal/pillarbox-playlist-next-item-button.js
- packages/pillarbox-playlist/src/components/modal/pillarbox-playlist-repeat-button.js
- packages/pillarbox-playlist/src/components/modal/pillarbox-playlist-shuffle-button.js
- packages/pillarbox-playlist/src/components/modal/pillarbox-previous-item-button.js
- packages/pillarbox-playlist/src/components/pillarbox-playlist-button.js
- packages/pillarbox-playlist/src/pillarbox-playlist-ui.js
- packages/pillarbox-playlist/vite.config.ui.js
Resolves https://github.com/SRGSSR/pillarbox-web-suite/issues/81 by replacing the usage of the videojs default button components with our own `SvgButton` component . This allows for more consistent customization.
**BREAKING CHANGE:** plugin options for dialog/buttons configuration are no longer passed through plugin options but via player root and controlBar options.
> feat(pillarbox-playlist): replace default buttons with custom svg-button components
